# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Minecraft
minecraft_version=[VERSIONED]
datapack_version=[VERSIONED]
# Fabric
fabric_version=0.16.5
fabric_api_version=[VERSIONED]
# Forge
forge_version=[VERSIONED]
forge_loader_version=[VERSIONED]
# NeoForge
neoforge_version=[VERSIONED]
neoforge_loader_version=[VERSIONED]

# Mod Info
maven_group=dev.hipposgrumm
modid=explosive_pitcher_pods
mod_name=Explosive Pitcher Pods
mod_version=1.1.0
mod_description=Pitcher pods explode now.\nAnnoy your friends to pieces by blowing their pitcher pod garden to pieces!
author=Hipposgrumm
license=All Rights Reserved

# Dependencies
minecraft_dep=[VERSIONED]