modLoader="javafml"
loaderVersion="[${neoforge_loader_version},)"
license="${license}"

[[mods]]
modId="${modid}"
version="${version}"
displayName="${mod_name}"
logoFile="assets/${modid}/mod.png"
authors="${author}"
description='''${mod_description}'''

[[mixins]]
config="${modid}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${modid}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${modid}]]
modId="minecraft"
type="required"
versionRange="${minecraft_dep}"
ordering="NONE"
side="BOTH"